tls:
  certificates:
    - certFile: /certs/hospital.crt
      keyFile: /certs/hospital.key

  stores:
    default:
      defaultCertificate:
        certFile: /certs/hospital.crt
        keyFile: /certs/hospital.key
